# 顶层 targets 移到了 [graph] 下
[graph]
targets = [
  #{ triple = "x86_64-unknown-linux-musl" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
# 旧版的 vulnerability / notice 整合到了 yanked 与各种 action 中
yanked = "warn"
ignore = [
  #"RUSTSEC-0000-0000",
]

[licenses]
# 设置匹配算法的置信度阈值
confidence-threshold = 0.8

# 替代旧版的 allow / deny / copyleft / allow-osi-fsf-free 组合
# 通过 expressions 列表控制允许或拒绝的 SPDX 许可表达式
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "CC0-1.0",
]

# 如需为特定 crate 解除限制，使用 exceptions
exceptions = [
  #{ allow = ["Zlib"], name = "adler32", version = "*" },
]

[licenses.private]
ignore = false
registries = [
  #"https://sekretz.com/registry"
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
